[versions]
kotlin = "1.5.30"
kotlin-coroutines = "1.5.2"

android-gradle = "7.0.2"
versionsPlugin-gradle = "0.39.0"

androidx-appCompat = "1.3.1"
androidx-cardView = "1.0.0"
androidx-constraintLayout = "2.1.0"
androidx-core = "1.6.0"
androidx-fragment = "1.3.6"
androidx-activity = "1.3.1"
androidx-lifecycle = "2.2.0"
androidx-preference = "1.1.1"
androidx-wear = "1.1.0"

google-autoFactory = "1.0.1"
google-autoValue = "1.8.2"
google-firebase-bom = "28.4.0"
google-firebase-crashlytics-gradle= "2.7.1"
google-material = "1.4.0"
google-playServices-gradle = "4.3.10"
google-playServices-location = "18.0.0"
google-playServices-wearable = "17.1.0"
google-protobuf-gradle = "0.8.17"
google-protobuf-liteGen = "3.0.0"
google-protobuf-liteRuntime = "3.0.1"
google-wearableLibrary = "2.8.1"

advancedRecyclerView = "1.0.0"
dagger = "2.38.1"
licensesDialog = "2.2.0"

junit4 = "4.13.2"
mockito-core = "3.12.4"
mockito-kotlin = "1.6.0"
robolectric = "4.6.1"

[libraries]
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin.coroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android.gradle" }
versionsPlugin-gradle = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsPlugin.gradle" }

androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx.appCompat" }
androidx-cardView = { module = "androidx.cardview:cardview", version.ref = "androidx.cardView" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx.constraintLayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx.core" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx.fragment" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx.activity" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx.lifecycle" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx.preference" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx.wear" }

google-autoFactory = { module = "com.google.auto.factory:auto-factory", version.ref = "google.autoFactory" }
google-autoValue = { module = "com.google.auto.value:auto-value", version.ref = "google.autoValue" }
google-autoValue-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "google.autoValue" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "google.firebase.bom" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref="google.firebase.crashlytics.gradle" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
google-material = { module = "com.google.android.material:material", version.ref = "google.material" }
google-wearableSupport = { module = "com.google.android.support:wearable", version.ref = "google.wearableLibrary" }
google-wearableLibrary = { module = "com.google.android.wearable:wearable", version.ref = "google.wearableLibrary" }
google-playServices-gradle = { module = "com.google.gms:google-services", version.ref = "google.playServices.gradle" }
google-playServices-location = { module = "com.google.android.gms:play-services-location", version.ref = "google.playServices.location" }
google-protobuf-gradle = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "google.protobuf.gradle" }
google-protobuf-liteGen = { module = "com.google.protobuf:protoc-gen-javalite", version.ref = "google.protobuf.liteGen" }
google-protobuf-liteRuntime = { module = "com.google.protobuf:protobuf-lite", version.ref = "google.protobuf.liteRuntime" }
google-playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "google.playServices.wearable" }

advancedRecyclerView = { module = "com.github.h6ah4i:android-advancedrecyclerview", version.ref = "advancedRecyclerView" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
licensesDialog = { module = "de.psdev.licensesdialog:licensesdialog", version.ref = "licensesDialog" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito.core" }
mockito-kotlin = { module = "com.nhaarman:mockito-kotlin", version.ref = "mockito.kotlin" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
